import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import { Toaster } from "sonner";
import Providers from "@/lib/provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amit's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <>
            <AppRouterCacheProvider>
              <Toaster position="top-center" />
              {children}
            </AppRouterCacheProvider>
          </>
        </body>
      </html>
    </Providers>
  );
}
